### ISSUE TITLE
Create Offer Sample Message & Corresponding Wiki

### ISSUE THREAD

**Issue by HTNG-Staff** [HTNG/Lightweight-Messaging#1]
18 September - during the workgroup call, the team decided that a sample message & wiki pair was needed for OFFERS (OFFER has been completed) - a collection of singlular offer(s)

**Comment by TheWix** [comment]
I am having second thoughts on this one after thinking about it more. 

This is primarily to support searching/filtering, correct? Why not something like /api/offers?param1=foo&param2=bar

Or even creating OffersSearch resource?

I haven't seen singular resources created for instances where we expect a collection to be returned before. Thoughts?

**Comment by jontebell** [comment]
The OfferCriteria resource is used to generate (as opposed to searching for or filtering) Offers. An Offers resource (and the Offers contained with it) may only exist for a limited time (often only 10 to 20 minutes).  Since offers expire the OfferCriteria can be re-used to create a new set of Offers.

 

GET /OfferCriteria/[OfferCriteriaID]/Offers will return a Collection of Offers as a resource.  Within the Time-to-live period the Offers collection can then be accessed via its ID and individual Offers can be retrieved as well.  Each Offer within the collection is also a resource but since these resources only have a limited life span we can use the OfferCriteria to create a new of Offer resources.  Remember that inventory is changing and the offers presented 10 minutes ago may no longer be available.

 

There are several issues with passing complex query parameters on the URL; these criteria can be very large and complex and may contain PII information.  Large queries may break certain browsers, and PII should never be passed as query params.  This solution is fully restful and addresses both of these concerns.

 

John

**Comment by TheWix** [comment]
Thanks, John! That was helpful. I am getting a clearer picture now. I didn't realize we'd be sending PII either. The caching (if needed) would happen against /OfferCriteria/[OfferCriteriaID]/Offers when it is requested.  The OfferCriteria would also have to be persisted on the server? So, at a later time I can issue a 
GET /OfferCriteria/1234/Offers and there server knows what I am talking about?


Also, is Offer a resource or just a schema?  What would a URI for 'Offer' be?

If I want an individual 'Offer' I would do something like:

api/offers/1

But by having both 'Offers' and 'Offer' it seems like we'd have some other URI like:

api/offers/1/offer 

I am just wondering when were refer to the new Offer resource?

**Comment by HTNG-Staff** [comment]
Offer/Offers completed
